Use options to set `schema_version` and `branch`
hubverse-org/hubAdmin pull request #87
Opened 2024-12-03 15:06 UTC by annakrystalli

This PR resolves #85 by setting the default values of `schema_version` and `branch` arguments to be set by options, with appropriate default values. Specifically:
- `schema_version` is set by `hubAdmin.schema_version` option
- `branch` is set by `hubAdmin.branch` option

I also added examples of how to set them. I thought about using `withr::with_options()` to temporarily set the options but I didn't as it wasn't the approach an actual user would use. So I ended up resetting the options at the end of each example block. Happy for suggestions of demonstrating this in a better way.

### Miscellaneous
- I also remove a couple of instances where `mockery::stub()` was being used and went ahead and removed all instances of tests which were configured against the `br-v4.0.0` branch, resolving #71

2024-12-03 16:47 UTC, zkamvar requested changes
Thank you! LGTM. There's one minor thing to include one more mocking of `askYesNo()` after line 68 of the test file.

2024-12-03 16:47 UTC, zkamvar commented on tests/testthat/test-create_task_id.R
there needs to be one more `askYesNo` mock after line 68 (when I run `devtools::test()`, it hangs here waiting for me to give it validation).

2024-12-03 16:47 UTC, zkamvar commented on DESCRIPTION
> -    mockery,
🔥 🔥 🔥 BURN IT DOWN!

2024-12-04 08:58 UTC, annakrystalli commented on tests/testthat/test-create_task_id.R
Hmm that's strange because the tests all run successfully when using the test button on the build panel as well as CI. `devtools::test()` also seems to be affected by the global environment when running. For example it seemed to be setting the `hubAdmin.schema_version` somewhere globally which was leaking into other tests (and lingered into the global environment afterwards) which does not happen when clicking the test button on the build panel or on CI. So not sure it's the best choice for running tests (see also note about [discrepancies in results in test results via `devtools::test()` and `R CMD CHECK`](https://r-pkgs.org/R-CMD-check.html#tests) in the R packages book). I've made changes in any case in da4e4cbbce135fbe7d967daaee64dd441e8045eb  so both pass but I think if it passes on CI it should be ok no?

2024-12-04 15:02 UTC, zkamvar approved these changes

2024-12-04 15:02 UTC, zkamvar commented on tests/testthat/test-create_task_id.R
> Hmm that's strange because the tests all run successfully when using the test button on the build panel as well as CI.

Ahhhh that's because RStudio does not run this in your default environment. The interactive element is what caught me up because `askYesNo` will return the default `TRUE` when called in a non-interactive environment:

``` r
callr::r(function() askYesNo("what"))
#> [1] TRUE
```

<sup>Created on 2024-12-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>


> I think if it passes on CI it should be ok no?

Kind of... this particular test was implicitly testing the default response, but the mock makes the test explicit and easier to reason about.

2024-12-04 15:02 UTC, zkamvar commented on tests/testthat/test-create_task_id.R
Nevertheless, I really appreciate the fix!

2024-12-04 15:33 UTC, merged